### ISSUE TITLE
Doesn't seem to work with images captured by OpenCamera app

### ISSUE THREAD

**Issue by Zhuinden** [miguelbcr/RxPaparazzo#90]
After receiving picture from [Open Camera](https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en), I get:

```
    java.io.IOException: Invalid marker: 89
        at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
        at android.media.ExifInterface.<init>(ExifInterface.java:1112)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.ImageUtils.copyExifTags(ImageUtils.java:348)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.ImageUtils.copyFileAndExifTags(ImageUtils.java:275)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.ImageUtils.scaleImage(ImageUtils.java:242)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.saveImageAndDeleteSourceFile(SaveFile.java:120)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.save(SaveFile.java:97)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.saveAndSendToMediaScanner(SaveFile.java:73)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.access$000(SaveFile.java:37)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile$1.apply(SaveFile.java:67)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile$1.apply(SaveFile.java:64)
```

while I do understand that there is a possibility that the camera returns an invalid EXIF tag, but the EXIF tags aren't as important to me as the actual image.

I don't think this should result in an internal failure within the library.

**Comment by edi233** [comment]
I got the same error when try to pick .gif file. Xiaomi Redmi Note 3 Pro.

**Comment by miguelbcr** [comment]
Thanks for reporting it!
I'll take a look...

**Comment by miguelbcr** [comment]
Hi @Zhuinden @edi233 !

I was not able to reproduce that crash, in spite of installing [Open Camera](https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en) 😞 

Also I think that crash should be catched by this [try-catch block ](https://github.com/miguelbcr/RxPaparazzo/blob/9ec1a6dc6b0b26e9087ef8671ff7f418844358ea/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/interactors/ImageUtils.java#L363) 🤔 

Anyway I've updated some libs and also replaced `import android.media.ExifInterface` by `import android.support.media.ExifInterface`. I think it should fix this crash...

Would you mind to try out this new RxPaparazzo lib -> [0.6.1-2.x](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.6.1-2.x)?

Please let me know if it works for you 🙏

**Comment by Zhuinden** [comment]
Is it released to repo? Readme still says `0.6.0-2.x`, just checking.

I'll try it out when I can, thanks.

**Comment by miguelbcr** [comment]
yeah, I've not updated the Readme yet, but you can use `0.6.1-2.x`

**Comment by Zhuinden** [comment]
Nope, still doesn't work:

```
08-28 13:21:07.038 7478-7518/com.acme.myapp.helloworld I/ExifInterface_JNI: Raw image not detected
08-28 13:21:07.953 634-1390/? I/Camera2ClientBase: Closed Camera 1. Client was: net.sourceforge.opencamera (PID 6807, UID 10175)
08-28 13:21:08.056 7478-7502/com.acme.myapp.helloworld D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=4697, firebase_screen_class(_sc)=UCropActivity, firebase_screen_id(_si)=6692670526037134516}]
08-28 13:21:08.124 7478-7502/com.acme.myapp.helloworld D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=UCropActivity, firebase_previous_id(_pi)=6692670526037134516, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=6692670526037134513}]
08-28 13:21:08.374 7478-7478/com.acme.myapp.helloworld I/FileData: Removing source file '/data/user/0/com.acme.myapp.helloworld/files/RxPaparazzo/PHOTO-20180828_1320_40251.jpg'
08-28 13:21:08.442 7478-7478/com.acme.myapp.helloworld D/ImageUtils: Could not copy exif tags from '/data/user/0/com.acme.myapp.helloworld/files/RxPaparazzo/CROPPED-20180828_1321_02884.jpg'
    java.io.IOException: ExifInterface only supports saving attributes on JPEG formats.
        at android.support.media.ExifInterface.saveAttributes(ExifInterface.java:4282)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.ImageUtils.copyExifTags(ImageUtils.java:361)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.ImageUtils.copyFileAndExifTags(ImageUtils.java:275)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.ImageUtils.scaleImage(ImageUtils.java:242)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.saveImageAndDeleteSourceFile(SaveFile.java:120)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.save(SaveFile.java:97)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.saveAndSendToMediaScanner(SaveFile.java:73)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile.access$000(SaveFile.java:37)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile$1.apply(SaveFile.java:67)
        at com.miguelbcr.ui.rx_paparazzo2.interactors.SaveFile$1.apply(SaveFile.java:64)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarXMapObservable.subscribeActual(ObservableScalarXMap.java:142)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmitScalar(ObservableFlatMap.java:237)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:146)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
        at rx_activity_result2.RxActivityResult$Builder$2.response(RxActivityResult.java:117)
        at rx_activity_result2.HolderActivity.onDestroy(HolderActivity.java:113)
        at android.app.Activity.performDestroy(Activity.java:6881)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-28 13:21:08.443 7478-7478/com.acme.myapp.helloworld I/FileData: Removing source file '/data/user/0/com.acme.myapp.helloworld/files/RxPaparazzo/CROPPED-20180828_1321_02884.jpg'
```

on the other hand, I need to mention that I'm on a Pixel XL and 7.1.1

I do not know if that affects anything

**Comment by miguelbcr** [comment]
well actually this message (`D/ImageUtils: Could not copy exif tags from '/data/user/0/com.acme.myapp.helloworld/files/RxPaparazzo/CROPPED-20180828_1321_02884.jpg'`) is from RxPaparazzo

so it is reaching the `catch` block in https://github.com/miguelbcr/RxPaparazzo/blob/9ec1a6dc6b0b26e9087ef8671ff7f418844358ea/rx_paparazzo/src/main/java/com/miguelbcr/ui/rx_paparazzo2/interactors/ImageUtils.java#L364

so I understand your app is not crashing at this point, it is only a Debug message warning you that EXIF tags are not copied successfully... but I don't know exactly the reason because the image has `JPG` extension (`CROPPED-20180828_1321_02884.jpg`) and you got this message:

``` 
java.io.IOException: ExifInterface only supports saving attributes on JPEG formats.
``` 

So the only I can think by now is that the image is `PNG` but we are renaming it to `JPG`.

Could you test the following and see if the you get the same error?:
- Use OpenCamera and don't crop the image
- Use another camera and crop/non-crop the image

**Comment by Zhuinden** [comment]
Hrmm we had following setup:

```
    private fun RxPaparazzo.SingleSelectionBuilder<Activity>.setupImageSelect() =
        useInternalStorage()
            .crop(UCrop.Options().apply {
                setCompressionFormat(Bitmap.CompressFormat.PNG)
                setAspectRatioOptions(0, AspectRatio("1:1", 1f, 1f))
            })
```

Replacing PNG with JPEG makes it not do anything instead. The error log is gone but apparently it was a red herring.

I think it's best if I post the consumer code, I wonder if it has something to do with the file being transient. BTW with built-in Camera app, it works.

    imageProfile.setImageURI("file:///${response.data().file.path}")

**Comment by miguelbcr** [comment]
what do you mean with `Replacing PNG with JPEG makes it not do anything instead` ? 
Does it works fine?

**Comment by Zhuinden** [comment]
No, the `setImageURI` still doesn't give me the new picture, but the error logs from the log are gone. Tried without cropping too and same thing, so maybe we are consuming it wrong.

Now I'm not sure what to do with it. ^_^

**Comment by miguelbcr** [comment]
try to debug without `.crop()` option and go step by step into the RxPaparazzo lib ckecking if `File(path).exits` till you reach `setImageURI()`

Btw, have you tested the sample app with OpenCamera? I tested it and worked 😕

**Comment by miguelbcr** [comment]
hi! 
any news on this?

**Comment by Zhuinden** [comment]
Just that it's still the same thing and I'm not sure where to look :smile:

**Comment by miguelbcr** [comment]
I'd try go step by step with the simpliest config till to use the `.crop()` option as I suggested here https://github.com/miguelbcr/RxPaparazzo/issues/90#issuecomment-416592511

Also you can use the sample app to make the test. In that way I could be able to reproduce the error as well in case there is any

**Comment by miguelbcr** [comment]
Hi @Zhuinden!
did you find out something?

Thanks!

**Comment by Zhuinden** [comment]
Nope, I'll just accept it as is
